exports.tweet = {
  created_at: 'Sun Jun 21 17:41:06 +0000 2015',
  id: 612676631493275600,
  id_str: '612676631493275648',
  text: '#bugshunt #challenge3 FO TL TL FO',
  source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
  truncated: false,
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user:
  { id: 3335249993,
    id_str: '3335249993',
    name: 'dummy_bugshunt',
    screen_name: 'dummy_bugshunt',
    location: '',
    url: null,
    description: null,
    protected: false,
    verified: false,
    followers_count: 0,
    friends_count: 0,
    listed_count: 0,
    favourites_count: 0,
    statuses_count: 7,
    created_at: 'Fri Jun 19 18:09:49 +0000 2015',
    utc_offset: null,
    time_zone: null,
    geo_enabled: false,
    lang: 'fr',
    contributors_enabled: false,
    is_translator: false,
    profile_background_color: 'C0DEED',
    profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_tile: false,
    profile_link_color: '0084B4',
    profile_sidebar_border_color: 'C0DEED',
    profile_sidebar_fill_color: 'DDEEF6',
    profile_text_color: '333333',
    profile_use_background_image: true,
    profile_image_url: 'http://abs.twimg.com/sticky/default_profile_images/default_profile_5_normal.png',
    profile_image_url_https: 'https://abs.twimg.com/sticky/default_profile_images/default_profile_5_normal.png',
    default_profile: true,
    default_profile_image: true,
    following: null,
    follow_request_sent: null,
    notifications: null },
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  retweet_count: 0,
  favorite_count: 0,
  entities:
  { hashtags: [ [Object], [Object] ],
    trends: [],
    urls: [],
    user_mentions: [],
    symbols: [] },
  favorited: false,
  retweeted: false,
  possibly_sensitive: false,
  filter_level: 'low',
  lang: 'en',
  timestamp_ms: '1434908466586'
};